# Generated by Django 4.2.13 on 2024-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_festival_approved_alter_festival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='location_name',
            field=models.CharField(default='England', max_length=255),
            preserve_default=False,
        ),
    ]
