# Generated by Django 4.2.13 on 2024-07-25 22:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_festival_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
