# Generated by Django 4.2.13 on 2024-07-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
